package com.gsfilter.filter

object FilterCatalog {

    val categories: List<FilterCategory> = listOf(
        FilterCategory(id = POPULAR, nameRes = R.string.gs_category_popular),
        FilterCategory(id = NATURAL, nameRes = R.string.gs_category_natural),
        FilterCategory(id = FILM, nameRes = R.string.gs_category_film),
        FilterCategory(id = VINTAGE, nameRes = R.string.gs_category_vintage),
        FilterCategory(id = WARM, nameRes = R.string.gs_category_warm),
        FilterCategory(id = COOL, nameRes = R.string.gs_category_cool),
        FilterCategory(id = PORTRAIT, nameRes = R.string.gs_category_portrait),
        FilterCategory(id = FOOD, nameRes = R.string.gs_category_food),
        FilterCategory(id = LANDSCAPE, nameRes = R.string.gs_category_landscape),
        FilterCategory(id = NIGHT, nameRes = R.string.gs_category_night),
        FilterCategory(id = CINEMATIC, nameRes = R.string.gs_category_cinematic),
        FilterCategory(id = BLACK_WHITE, nameRes = R.string.gs_category_black_white),
        FilterCategory(id = AESTHETIC, nameRes = R.string.gs_category_aesthetic),
        FilterCategory(id = CREATIVE, nameRes = R.string.gs_category_creative),
        FilterCategory(id = ART, nameRes = R.string.gs_category_art),
    )

    val options: List<FilterOption> = listOf(
        FilterOption(
            id = ORIGINAL,
            categoryIds = emptySet(),
            nameRes = R.string.gs_action_original,
            recipe = FilterRecipe(),
        ),
        FilterOption(
            id = "fresh",
            categoryIds = setOf(POPULAR, NATURAL),
            nameRes = R.string.gs_filter_fresh,
            recipe = FilterRecipe(
                redShift = 4,
                greenShift = 6,
                blueShift = 4,
                adjustments = Adjustments(
                    exposure = 6,
                    contrast = 4,
                    saturation = 8,
                    vibrance = 12,
                    clarity = 4,
                ),
            ),
        ),
        FilterOption(
            id = "portra",
            categoryIds = setOf(FILM, PORTRAIT),
            nameRes = R.string.gs_filter_portra,
            recipe = FilterRecipe(
                redShift = 10,
                greenShift = 3,
                blueShift = -4,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -6,
                    highlights = -12,
                    shadows = 8,
                    saturation = -6,
                    temperature = 6,
                    tint = 4,
                    sharpness = 8,
                ),
            ),
        ),
        FilterOption(
            id = "retro",
            categoryIds = setOf(VINTAGE),
            nameRes = R.string.gs_filter_retro,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = -4,
                blueShift = -12,
                adjustments = Adjustments(
                    contrast = -12,
                    saturation = -18,
                    temperature = 12,
                    fade = 20,
                    vignette = 10,
                    grain = 14,
                ),
            ),
        ),
        FilterOption(
            id = "warm",
            categoryIds = setOf(POPULAR, WARM),
            nameRes = R.string.gs_filter_warm,
            recipe = FilterRecipe(
                redShift = 18,
                greenShift = 6,
                blueShift = -10,
                adjustments = Adjustments(
                    exposure = 4,
                    contrast = 6,
                    saturation = 8,
                    temperature = 18,
                ),
            ),
        ),
        FilterOption(
            id = "cool",
            categoryIds = setOf(COOL),
            nameRes = R.string.gs_filter_cool,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 4,
                blueShift = 18,
                adjustments = Adjustments(
                    contrast = 4,
                    saturation = -4,
                    temperature = -18,
                    tint = -6,
                    clarity = 8,
                ),
            ),
        ),
        FilterOption(
            id = "skin",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_skin,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = 2,
                blueShift = -6,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -8,
                    highlights = -10,
                    shadows = 6,
                    saturation = -4,
                    temperature = 8,
                    tint = 5,
                    sharpness = 4,
                ),
            ),
        ),
        FilterOption(
            id = "tasty",
            categoryIds = setOf(POPULAR, FOOD),
            nameRes = R.string.gs_filter_tasty,
            recipe = FilterRecipe(
                redShift = 14,
                greenShift = 8,
                blueShift = -4,
                adjustments = Adjustments(
                    contrast = 8,
                    saturation = 16,
                    vibrance = 14,
                    temperature = 8,
                    clarity = 8,
                ),
            ),
        ),
        FilterOption(
            id = "cinema",
            categoryIds = setOf(CINEMATIC),
            nameRes = R.string.gs_filter_cinema,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 8,
                blueShift = 10,
                adjustments = Adjustments(
                    exposure = -4,
                    contrast = 18,
                    highlights = -18,
                    shadows = -8,
                    saturation = -8,
                    clarity = 10,
                    vignette = 18,
                ),
            ),
        ),
        FilterOption(
            id = "mono",
            categoryIds = setOf(POPULAR, BLACK_WHITE),
            nameRes = R.string.gs_filter_mono,
            recipe = FilterRecipe(
                isMonochrome = true,
                adjustments = Adjustments(
                    contrast = 14,
                    clarity = 8,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "clear",
            categoryIds = setOf(POPULAR, NATURAL),
            nameRes = R.string.gs_filter_clear,
            recipe = FilterRecipe(
                redShift = 2,
                greenShift = 4,
                blueShift = 3,
                adjustments = Adjustments(
                    exposure = 4,
                    contrast = 6,
                    highlights = -8,
                    shadows = 6,
                    vibrance = 8,
                    clarity = 6,
                ),
            ),
        ),
        FilterOption(
            id = "airy",
            categoryIds = setOf(NATURAL),
            nameRes = R.string.gs_filter_airy,
            recipe = FilterRecipe(
                redShift = 4,
                greenShift = 4,
                blueShift = 6,
                adjustments = Adjustments(
                    brightness = 6,
                    exposure = 6,
                    contrast = -10,
                    highlights = -10,
                    saturation = -6,
                    fade = 8,
                ),
            ),
        ),
        FilterOption(
            id = "fuji",
            categoryIds = setOf(FILM),
            nameRes = R.string.gs_filter_fuji,
            recipe = FilterRecipe(
                redShift = 2,
                greenShift = 8,
                blueShift = 6,
                adjustments = Adjustments(
                    contrast = 10,
                    highlights = -14,
                    shadows = 6,
                    saturation = 8,
                    temperature = -4,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "gold",
            categoryIds = setOf(POPULAR, FILM, WARM),
            nameRes = R.string.gs_filter_gold,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = 8,
                blueShift = -8,
                adjustments = Adjustments(
                    contrast = 8,
                    highlights = -8,
                    saturation = 10,
                    temperature = 16,
                    fade = 6,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "classic",
            categoryIds = setOf(VINTAGE),
            nameRes = R.string.gs_filter_classic,
            recipe = FilterRecipe(
                redShift = 10,
                greenShift = 0,
                blueShift = -10,
                adjustments = Adjustments(
                    contrast = -8,
                    saturation = -14,
                    temperature = 8,
                    tint = 4,
                    fade = 16,
                    vignette = 12,
                    grain = 10,
                ),
            ),
        ),
        FilterOption(
            id = "honey",
            categoryIds = setOf(WARM),
            nameRes = R.string.gs_filter_honey,
            recipe = FilterRecipe(
                redShift = 20,
                greenShift = 8,
                blueShift = -12,
                adjustments = Adjustments(
                    exposure = 6,
                    contrast = 4,
                    saturation = 8,
                    temperature = 22,
                    highlights = -6,
                ),
            ),
        ),
        FilterOption(
            id = "arctic",
            categoryIds = setOf(COOL),
            nameRes = R.string.gs_filter_arctic,
            recipe = FilterRecipe(
                redShift = -12,
                greenShift = 2,
                blueShift = 22,
                adjustments = Adjustments(
                    exposure = 2,
                    contrast = 8,
                    saturation = -8,
                    temperature = -24,
                    clarity = 10,
                ),
            ),
        ),
        FilterOption(
            id = "peach",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_peach,
            recipe = FilterRecipe(
                redShift = 14,
                greenShift = 4,
                blueShift = -8,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -10,
                    highlights = -8,
                    saturation = -4,
                    temperature = 10,
                    tint = 8,
                    sharpness = 4,
                ),
            ),
        ),
        FilterOption(
            id = "crispy",
            categoryIds = setOf(FOOD),
            nameRes = R.string.gs_filter_crispy,
            recipe = FilterRecipe(
                redShift = 10,
                greenShift = 10,
                blueShift = -4,
                adjustments = Adjustments(
                    contrast = 14,
                    saturation = 18,
                    vibrance = 18,
                    clarity = 14,
                    sharpness = 10,
                ),
            ),
        ),
        FilterOption(
            id = "teal_orange",
            categoryIds = setOf(POPULAR, CINEMATIC),
            nameRes = R.string.gs_filter_teal_orange,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = 4,
                blueShift = 8,
                adjustments = Adjustments(
                    exposure = -4,
                    contrast = 22,
                    highlights = -16,
                    shadows = -10,
                    saturation = -6,
                    temperature = 8,
                    tint = -8,
                    clarity = 12,
                    vignette = 20,
                ),
            ),
        ),
        FilterOption(
            id = "noir",
            categoryIds = setOf(CINEMATIC, BLACK_WHITE),
            nameRes = R.string.gs_filter_noir,
            recipe = FilterRecipe(
                isMonochrome = true,
                adjustments = Adjustments(
                    exposure = -6,
                    contrast = 26,
                    highlights = -20,
                    shadows = -12,
                    clarity = 16,
                    vignette = 24,
                    grain = 12,
                ),
            ),
        ),
        FilterOption(
            id = "matte",
            categoryIds = setOf(BLACK_WHITE),
            nameRes = R.string.gs_filter_matte,
            recipe = FilterRecipe(
                isMonochrome = true,
                adjustments = Adjustments(
                    contrast = -8,
                    highlights = -8,
                    shadows = 10,
                    fade = 18,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "cream",
            categoryIds = setOf(POPULAR, PORTRAIT),
            nameRes = R.string.gs_filter_cream,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = 6,
                blueShift = -6,
                adjustments = Adjustments(
                    brightness = 6,
                    contrast = -12,
                    highlights = -8,
                    shadows = 8,
                    saturation = -6,
                    temperature = 8,
                    tint = 4,
                    fade = 6,
                ),
            ),
        ),
        FilterOption(
            id = "glow",
            categoryIds = setOf(POPULAR, NATURAL, PORTRAIT),
            nameRes = R.string.gs_filter_glow,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 6,
                blueShift = 2,
                adjustments = Adjustments(
                    brightness = 8,
                    exposure = 6,
                    contrast = -8,
                    highlights = -12,
                    shadows = 6,
                    vibrance = 10,
                    clarity = -6,
                ),
            ),
        ),
        FilterOption(
            id = "kodak",
            categoryIds = setOf(FILM, VINTAGE),
            nameRes = R.string.gs_filter_kodak,
            recipe = FilterRecipe(
                redShift = 14,
                greenShift = 6,
                blueShift = -6,
                adjustments = Adjustments(
                    contrast = 12,
                    highlights = -12,
                    shadows = 4,
                    saturation = 10,
                    temperature = 6,
                    fade = 8,
                    grain = 10,
                ),
            ),
        ),
        FilterOption(
            id = "sunset",
            categoryIds = setOf(POPULAR, WARM),
            nameRes = R.string.gs_filter_sunset,
            recipe = FilterRecipe(
                redShift = 24,
                greenShift = 6,
                blueShift = -18,
                adjustments = Adjustments(
                    exposure = -2,
                    contrast = 12,
                    highlights = -16,
                    saturation = 12,
                    vibrance = 10,
                    temperature = 24,
                    vignette = 10,
                ),
            ),
        ),
        FilterOption(
            id = "mist",
            categoryIds = setOf(COOL, NATURAL),
            nameRes = R.string.gs_filter_mist,
            recipe = FilterRecipe(
                redShift = -4,
                greenShift = 4,
                blueShift = 12,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -14,
                    highlights = -12,
                    shadows = 10,
                    saturation = -12,
                    temperature = -10,
                    fade = 12,
                ),
            ),
        ),
        FilterOption(
            id = "cafe",
            categoryIds = setOf(FOOD, WARM),
            nameRes = R.string.gs_filter_cafe,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = 8,
                blueShift = -10,
                adjustments = Adjustments(
                    contrast = 6,
                    saturation = 10,
                    vibrance = 8,
                    temperature = 16,
                    tint = 4,
                    fade = 8,
                ),
            ),
        ),
        FilterOption(
            id = "drama",
            categoryIds = setOf(CINEMATIC),
            nameRes = R.string.gs_filter_drama,
            recipe = FilterRecipe(
                redShift = -4,
                greenShift = 4,
                blueShift = 8,
                adjustments = Adjustments(
                    exposure = -8,
                    contrast = 28,
                    highlights = -22,
                    shadows = -16,
                    saturation = -12,
                    clarity = 18,
                    vignette = 26,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "epic",
            categoryIds = setOf(CINEMATIC),
            nameRes = R.string.gs_filter_epic,
            recipe = FilterRecipe(
                redShift = 6,
                greenShift = 2,
                blueShift = 8,
                adjustments = Adjustments(
                    exposure = -4,
                    contrast = 24,
                    highlights = -20,
                    shadows = -8,
                    saturation = -6,
                    clarity = 18,
                    vignette = 20,
                ),
            ),
        ),
        FilterOption(
            id = "blockbuster",
            categoryIds = setOf(POPULAR, CINEMATIC),
            nameRes = R.string.gs_filter_blockbuster,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = 2,
                blueShift = 10,
                adjustments = Adjustments(
                    exposure = -6,
                    contrast = 30,
                    highlights = -24,
                    shadows = -14,
                    saturation = -10,
                    temperature = 10,
                    tint = -10,
                    clarity = 20,
                    vignette = 24,
                    grain = 4,
                ),
            ),
        ),
        FilterOption(
            id = "arthouse",
            categoryIds = setOf(CINEMATIC, VINTAGE),
            nameRes = R.string.gs_filter_arthouse,
            recipe = FilterRecipe(
                redShift = 4,
                greenShift = -2,
                blueShift = 6,
                adjustments = Adjustments(
                    brightness = -2,
                    contrast = -6,
                    highlights = -14,
                    shadows = 12,
                    saturation = -18,
                    tint = 6,
                    fade = 14,
                    vignette = 16,
                    grain = 12,
                ),
            ),
        ),
        FilterOption(
            id = "silver",
            categoryIds = setOf(BLACK_WHITE),
            nameRes = R.string.gs_filter_silver,
            recipe = FilterRecipe(
                isMonochrome = true,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = 10,
                    highlights = -10,
                    shadows = 8,
                    clarity = 10,
                    fade = 6,
                ),
            ),
        ),
        FilterOption(
            id = "pure",
            categoryIds = setOf(NATURAL),
            nameRes = R.string.gs_filter_pure,
            recipe = FilterRecipe(
                redShift = 2,
                greenShift = 3,
                blueShift = 2,
                adjustments = Adjustments(
                    exposure = 3,
                    contrast = -4,
                    highlights = -6,
                    shadows = 4,
                    saturation = -2,
                ),
            ),
        ),
        FilterOption(
            id = "clean",
            categoryIds = setOf(POPULAR, NATURAL),
            nameRes = R.string.gs_filter_clean,
            recipe = FilterRecipe(
                redShift = 1,
                greenShift = 4,
                blueShift = 4,
                adjustments = Adjustments(
                    brightness = 3,
                    exposure = 4,
                    contrast = 6,
                    highlights = -8,
                    vibrance = 6,
                    clarity = 8,
                ),
            ),
        ),
        FilterOption(
            id = "soft",
            categoryIds = setOf(POPULAR, NATURAL, PORTRAIT),
            nameRes = R.string.gs_filter_soft,
            recipe = FilterRecipe(
                redShift = 6,
                greenShift = 4,
                blueShift = 2,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -12,
                    highlights = -10,
                    shadows = 8,
                    saturation = -8,
                    clarity = -8,
                    fade = 6,
                ),
            ),
        ),
        FilterOption(
            id = "bright",
            categoryIds = setOf(NATURAL),
            nameRes = R.string.gs_filter_bright,
            recipe = FilterRecipe(
                redShift = 3,
                greenShift = 4,
                blueShift = 5,
                adjustments = Adjustments(
                    brightness = 8,
                    exposure = 8,
                    contrast = -6,
                    highlights = -14,
                    shadows = 6,
                    vibrance = 8,
                ),
            ),
        ),
        FilterOption(
            id = "clear_day",
            categoryIds = setOf(NATURAL, LANDSCAPE),
            nameRes = R.string.gs_filter_clear_day,
            recipe = FilterRecipe(
                redShift = 2,
                greenShift = 6,
                blueShift = 8,
                adjustments = Adjustments(
                    exposure = 5,
                    contrast = 8,
                    highlights = -12,
                    shadows = 6,
                    saturation = 6,
                    clarity = 10,
                ),
            ),
        ),
        FilterOption(
            id = "blush",
            categoryIds = setOf(PORTRAIT, AESTHETIC),
            nameRes = R.string.gs_filter_blush,
            recipe = FilterRecipe(
                redShift = 14,
                greenShift = 2,
                blueShift = -6,
                adjustments = Adjustments(
                    brightness = 5,
                    contrast = -10,
                    highlights = -8,
                    shadows = 6,
                    saturation = -4,
                    temperature = 6,
                    tint = 10,
                    fade = 4,
                ),
            ),
        ),
        FilterOption(
            id = "skin_soft",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_skin_soft,
            recipe = FilterRecipe(
                redShift = 10,
                greenShift = 2,
                blueShift = -4,
                adjustments = Adjustments(
                    brightness = 6,
                    contrast = -14,
                    highlights = -12,
                    shadows = 8,
                    saturation = -8,
                    temperature = 6,
                    tint = 4,
                    sharpness = 2,
                    clarity = -10,
                ),
            ),
        ),
        FilterOption(
            id = "rosy",
            categoryIds = setOf(PORTRAIT, AESTHETIC),
            nameRes = R.string.gs_filter_rosy,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = 4,
                blueShift = -6,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -8,
                    saturation = -2,
                    temperature = 8,
                    tint = 12,
                    fade = 5,
                ),
            ),
        ),
        FilterOption(
            id = "tan",
            categoryIds = setOf(PORTRAIT, WARM),
            nameRes = R.string.gs_filter_tan,
            recipe = FilterRecipe(
                redShift = 18,
                greenShift = 8,
                blueShift = -12,
                adjustments = Adjustments(
                    exposure = -2,
                    contrast = 8,
                    highlights = -10,
                    shadows = 6,
                    saturation = 4,
                    temperature = 16,
                    vignette = 8,
                ),
            ),
        ),
        FilterOption(
            id = "beauty",
            categoryIds = setOf(POPULAR, PORTRAIT),
            nameRes = R.string.gs_filter_beauty,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 4,
                blueShift = -2,
                adjustments = Adjustments(
                    brightness = 6,
                    exposure = 4,
                    contrast = -8,
                    highlights = -10,
                    shadows = 6,
                    vibrance = 6,
                    clarity = -6,
                ),
            ),
        ),
        FilterOption(
            id = "amber",
            categoryIds = setOf(WARM),
            nameRes = R.string.gs_filter_amber,
            recipe = FilterRecipe(
                redShift = 22,
                greenShift = 8,
                blueShift = -14,
                adjustments = Adjustments(
                    contrast = 8,
                    saturation = 8,
                    temperature = 24,
                    shadows = 4,
                    fade = 4,
                ),
            ),
        ),
        FilterOption(
            id = "caramel",
            categoryIds = setOf(WARM, AESTHETIC),
            nameRes = R.string.gs_filter_caramel,
            recipe = FilterRecipe(
                redShift = 20,
                greenShift = 10,
                blueShift = -14,
                adjustments = Adjustments(
                    contrast = 6,
                    highlights = -8,
                    shadows = 10,
                    saturation = 6,
                    temperature = 18,
                    fade = 8,
                ),
            ),
        ),
        FilterOption(
            id = "golden_hour",
            categoryIds = setOf(POPULAR, WARM, LANDSCAPE),
            nameRes = R.string.gs_filter_golden_hour,
            recipe = FilterRecipe(
                redShift = 26,
                greenShift = 10,
                blueShift = -18,
                adjustments = Adjustments(
                    exposure = 3,
                    contrast = 12,
                    highlights = -18,
                    shadows = 8,
                    saturation = 10,
                    vibrance = 10,
                    temperature = 26,
                    vignette = 8,
                ),
            ),
        ),
        FilterOption(
            id = "cozy",
            categoryIds = setOf(WARM, AESTHETIC),
            nameRes = R.string.gs_filter_cozy,
            recipe = FilterRecipe(
                redShift = 18,
                greenShift = 8,
                blueShift = -10,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -4,
                    highlights = -10,
                    shadows = 8,
                    saturation = 4,
                    temperature = 18,
                    fade = 8,
                ),
            ),
        ),
        FilterOption(
            id = "ice",
            categoryIds = setOf(COOL),
            nameRes = R.string.gs_filter_ice,
            recipe = FilterRecipe(
                redShift = -10,
                greenShift = 2,
                blueShift = 24,
                adjustments = Adjustments(
                    exposure = 4,
                    contrast = 6,
                    saturation = -10,
                    temperature = -26,
                    tint = -4,
                    clarity = 8,
                ),
            ),
        ),
        FilterOption(
            id = "blue_mist",
            categoryIds = setOf(COOL, NATURAL),
            nameRes = R.string.gs_filter_blue_mist,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 4,
                blueShift = 18,
                adjustments = Adjustments(
                    brightness = 5,
                    contrast = -16,
                    highlights = -14,
                    shadows = 10,
                    saturation = -14,
                    temperature = -18,
                    fade = 14,
                ),
            ),
        ),
        FilterOption(
            id = "winter",
            categoryIds = setOf(COOL, LANDSCAPE),
            nameRes = R.string.gs_filter_winter,
            recipe = FilterRecipe(
                redShift = -12,
                greenShift = 2,
                blueShift = 20,
                adjustments = Adjustments(
                    exposure = 3,
                    contrast = 10,
                    highlights = -16,
                    saturation = -12,
                    temperature = -22,
                    clarity = 12,
                ),
            ),
        ),
        FilterOption(
            id = "steel",
            categoryIds = setOf(COOL, CINEMATIC),
            nameRes = R.string.gs_filter_steel,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 0,
                blueShift = 14,
                adjustments = Adjustments(
                    exposure = -2,
                    contrast = 18,
                    highlights = -16,
                    shadows = -8,
                    saturation = -18,
                    temperature = -18,
                    clarity = 14,
                ),
            ),
        ),
        FilterOption(
            id = "cyan_clean",
            categoryIds = setOf(COOL),
            nameRes = R.string.gs_filter_cyan_clean,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 8,
                blueShift = 16,
                adjustments = Adjustments(
                    exposure = 4,
                    contrast = 8,
                    highlights = -10,
                    saturation = -4,
                    temperature = -12,
                    tint = -8,
                    clarity = 10,
                ),
            ),
        ),
        FilterOption(
            id = "grain_film",
            categoryIds = setOf(FILM, VINTAGE),
            nameRes = R.string.gs_filter_grain_film,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 4,
                blueShift = -4,
                adjustments = Adjustments(
                    contrast = 10,
                    highlights = -14,
                    shadows = 6,
                    saturation = 4,
                    temperature = 4,
                    fade = 6,
                    grain = 18,
                ),
            ),
        ),
        FilterOption(
            id = "fade",
            categoryIds = setOf(VINTAGE, AESTHETIC),
            nameRes = R.string.gs_filter_fade,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 2,
                blueShift = -6,
                adjustments = Adjustments(
                    contrast = -16,
                    highlights = -12,
                    shadows = 14,
                    saturation = -16,
                    fade = 24,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "dust",
            categoryIds = setOf(VINTAGE),
            nameRes = R.string.gs_filter_dust,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = 4,
                blueShift = -10,
                adjustments = Adjustments(
                    contrast = -10,
                    highlights = -10,
                    shadows = 8,
                    saturation = -18,
                    temperature = 10,
                    fade = 18,
                    vignette = 10,
                    grain = 16,
                ),
            ),
        ),
        FilterOption(
            id = "oldie",
            categoryIds = setOf(VINTAGE),
            nameRes = R.string.gs_filter_oldie,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = 4,
                blueShift = -14,
                adjustments = Adjustments(
                    brightness = -2,
                    contrast = -14,
                    highlights = -10,
                    shadows = 12,
                    saturation = -22,
                    temperature = 14,
                    tint = 4,
                    fade = 22,
                    grain = 14,
                ),
            ),
        ),
        FilterOption(
            id = "nineties",
            categoryIds = setOf(VINTAGE, AESTHETIC),
            nameRes = R.string.gs_filter_nineties,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = -2,
                blueShift = -8,
                adjustments = Adjustments(
                    contrast = -4,
                    highlights = -14,
                    shadows = 10,
                    saturation = -10,
                    tint = 8,
                    fade = 12,
                    grain = 10,
                ),
            ),
        ),
        FilterOption(
            id = "retro_matte",
            categoryIds = setOf(VINTAGE, BLACK_WHITE),
            nameRes = R.string.gs_filter_retro_matte,
            recipe = FilterRecipe(
                redShift = 6,
                greenShift = 0,
                blueShift = -8,
                adjustments = Adjustments(
                    contrast = -10,
                    highlights = -10,
                    shadows = 12,
                    saturation = -24,
                    fade = 20,
                    grain = 10,
                ),
            ),
        ),
        FilterOption(
            id = "dark_mood",
            categoryIds = setOf(CINEMATIC),
            nameRes = R.string.gs_filter_dark_mood,
            recipe = FilterRecipe(
                redShift = -4,
                greenShift = 2,
                blueShift = 6,
                adjustments = Adjustments(
                    exposure = -12,
                    contrast = 26,
                    highlights = -20,
                    shadows = -18,
                    saturation = -16,
                    clarity = 16,
                    vignette = 30,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "bleach",
            categoryIds = setOf(CINEMATIC, FILM),
            nameRes = R.string.gs_filter_bleach,
            recipe = FilterRecipe(
                redShift = 6,
                greenShift = 2,
                blueShift = -2,
                adjustments = Adjustments(
                    exposure = 2,
                    contrast = 28,
                    highlights = -18,
                    shadows = -10,
                    saturation = -28,
                    clarity = 18,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "high_contrast",
            categoryIds = setOf(BLACK_WHITE),
            nameRes = R.string.gs_filter_high_contrast,
            recipe = FilterRecipe(
                isMonochrome = true,
                adjustments = Adjustments(
                    exposure = -2,
                    contrast = 34,
                    highlights = -16,
                    shadows = -12,
                    clarity = 18,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "soft_mono",
            categoryIds = setOf(BLACK_WHITE, PORTRAIT),
            nameRes = R.string.gs_filter_soft_mono,
            recipe = FilterRecipe(
                isMonochrome = true,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -8,
                    highlights = -8,
                    shadows = 8,
                    clarity = -4,
                    fade = 12,
                    grain = 4,
                ),
            ),
        ),
        FilterOption(
            id = "sweet",
            categoryIds = setOf(FOOD, AESTHETIC),
            nameRes = R.string.gs_filter_sweet,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = 8,
                blueShift = -4,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = 4,
                    saturation = 14,
                    vibrance = 14,
                    temperature = 8,
                    clarity = 6,
                ),
            ),
        ),
        FilterOption(
            id = "fresh_food",
            categoryIds = setOf(FOOD, NATURAL),
            nameRes = R.string.gs_filter_fresh_food,
            recipe = FilterRecipe(
                redShift = 6,
                greenShift = 10,
                blueShift = 0,
                adjustments = Adjustments(
                    exposure = 4,
                    contrast = 10,
                    highlights = -10,
                    saturation = 12,
                    vibrance = 18,
                    temperature = 2,
                    clarity = 10,
                ),
            ),
        ),
        FilterOption(
            id = "warm_plate",
            categoryIds = setOf(FOOD, WARM),
            nameRes = R.string.gs_filter_warm_plate,
            recipe = FilterRecipe(
                redShift = 18,
                greenShift = 10,
                blueShift = -8,
                adjustments = Adjustments(
                    contrast = 8,
                    highlights = -10,
                    saturation = 14,
                    vibrance = 12,
                    temperature = 16,
                    clarity = 8,
                ),
            ),
        ),
        FilterOption(
            id = "vivid",
            categoryIds = setOf(POPULAR, LANDSCAPE),
            nameRes = R.string.gs_filter_vivid,
            recipe = FilterRecipe(
                redShift = 4,
                greenShift = 8,
                blueShift = 4,
                adjustments = Adjustments(
                    exposure = 4,
                    contrast = 16,
                    highlights = -14,
                    shadows = 6,
                    saturation = 18,
                    vibrance = 18,
                    clarity = 14,
                ),
            ),
        ),
        FilterOption(
            id = "forest",
            categoryIds = setOf(LANDSCAPE),
            nameRes = R.string.gs_filter_forest,
            recipe = FilterRecipe(
                redShift = -4,
                greenShift = 18,
                blueShift = -4,
                adjustments = Adjustments(
                    exposure = 2,
                    contrast = 12,
                    highlights = -16,
                    shadows = 8,
                    saturation = 12,
                    vibrance = 16,
                    temperature = -4,
                    clarity = 12,
                ),
            ),
        ),
        FilterOption(
            id = "ocean",
            categoryIds = setOf(LANDSCAPE, COOL),
            nameRes = R.string.gs_filter_ocean,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 8,
                blueShift = 20,
                adjustments = Adjustments(
                    exposure = 3,
                    contrast = 12,
                    highlights = -14,
                    saturation = 10,
                    vibrance = 16,
                    temperature = -14,
                    clarity = 14,
                ),
            ),
        ),
        FilterOption(
            id = "sky",
            categoryIds = setOf(LANDSCAPE, COOL),
            nameRes = R.string.gs_filter_sky,
            recipe = FilterRecipe(
                redShift = -4,
                greenShift = 6,
                blueShift = 18,
                adjustments = Adjustments(
                    brightness = 3,
                    exposure = 4,
                    contrast = 8,
                    highlights = -18,
                    saturation = 8,
                    vibrance = 14,
                    temperature = -10,
                    clarity = 10,
                ),
            ),
        ),
        FilterOption(
            id = "travel",
            categoryIds = setOf(POPULAR, LANDSCAPE),
            nameRes = R.string.gs_filter_travel,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 8,
                blueShift = 2,
                adjustments = Adjustments(
                    exposure = 4,
                    contrast = 14,
                    highlights = -12,
                    shadows = 6,
                    saturation = 12,
                    vibrance = 14,
                    temperature = 6,
                    clarity = 12,
                ),
            ),
        ),
        FilterOption(
            id = "green_pop",
            categoryIds = setOf(LANDSCAPE),
            nameRes = R.string.gs_filter_green_pop,
            recipe = FilterRecipe(
                redShift = -2,
                greenShift = 20,
                blueShift = -6,
                adjustments = Adjustments(
                    contrast = 10,
                    highlights = -12,
                    shadows = 6,
                    saturation = 14,
                    vibrance = 18,
                    temperature = -2,
                    clarity = 12,
                ),
            ),
        ),
        FilterOption(
            id = "beige",
            categoryIds = setOf(AESTHETIC, PORTRAIT),
            nameRes = R.string.gs_filter_beige,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = 6,
                blueShift = -8,
                adjustments = Adjustments(
                    brightness = 5,
                    contrast = -12,
                    highlights = -10,
                    shadows = 10,
                    saturation = -14,
                    temperature = 10,
                    fade = 10,
                ),
            ),
        ),
        FilterOption(
            id = "latte",
            categoryIds = setOf(AESTHETIC, WARM),
            nameRes = R.string.gs_filter_latte,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = 8,
                blueShift = -10,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -10,
                    highlights = -12,
                    shadows = 12,
                    saturation = -10,
                    temperature = 14,
                    fade = 12,
                ),
            ),
        ),
        FilterOption(
            id = "pink",
            categoryIds = setOf(AESTHETIC, PORTRAIT),
            nameRes = R.string.gs_filter_pink,
            recipe = FilterRecipe(
                redShift = 18,
                greenShift = 2,
                blueShift = 4,
                adjustments = Adjustments(
                    brightness = 6,
                    contrast = -10,
                    highlights = -8,
                    saturation = -8,
                    temperature = 4,
                    tint = 18,
                    fade = 8,
                ),
            ),
        ),
        FilterOption(
            id = "dreamy",
            categoryIds = setOf(AESTHETIC, NATURAL),
            nameRes = R.string.gs_filter_dreamy,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 4,
                blueShift = 8,
                adjustments = Adjustments(
                    brightness = 8,
                    exposure = 4,
                    contrast = -18,
                    highlights = -14,
                    shadows = 12,
                    saturation = -8,
                    clarity = -12,
                    fade = 12,
                ),
            ),
        ),
        FilterOption(
            id = "minimal",
            categoryIds = setOf(AESTHETIC, NATURAL),
            nameRes = R.string.gs_filter_minimal,
            recipe = FilterRecipe(
                redShift = 2,
                greenShift = 2,
                blueShift = 2,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -8,
                    highlights = -8,
                    shadows = 6,
                    saturation = -18,
                    fade = 6,
                ),
            ),
        ),
        FilterOption(
            id = "neon",
            categoryIds = setOf(POPULAR, NIGHT, CREATIVE),
            nameRes = R.string.gs_filter_neon,
            recipe = FilterRecipe(
                redShift = 10,
                greenShift = -4,
                blueShift = 18,
                adjustments = Adjustments(
                    exposure = -4,
                    contrast = 24,
                    highlights = -24,
                    shadows = -12,
                    saturation = 16,
                    vibrance = 22,
                    tint = 14,
                    clarity = 18,
                    vignette = 22,
                ),
            ),
        ),
        FilterOption(
            id = "city",
            categoryIds = setOf(NIGHT, CINEMATIC),
            nameRes = R.string.gs_filter_city,
            recipe = FilterRecipe(
                redShift = 4,
                greenShift = 2,
                blueShift = 12,
                adjustments = Adjustments(
                    exposure = -2,
                    contrast = 20,
                    highlights = -20,
                    shadows = -8,
                    saturation = -4,
                    temperature = -8,
                    clarity = 14,
                    vignette = 18,
                ),
            ),
        ),
        FilterOption(
            id = "night",
            categoryIds = setOf(NIGHT),
            nameRes = R.string.gs_filter_night,
            recipe = FilterRecipe(
                redShift = -6,
                greenShift = 0,
                blueShift = 16,
                adjustments = Adjustments(
                    exposure = -10,
                    contrast = 22,
                    highlights = -18,
                    shadows = 10,
                    saturation = -10,
                    temperature = -18,
                    clarity = 12,
                    vignette = 24,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "blue_hour",
            categoryIds = setOf(NIGHT, COOL, LANDSCAPE),
            nameRes = R.string.gs_filter_blue_hour,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 4,
                blueShift = 18,
                adjustments = Adjustments(
                    exposure = -4,
                    contrast = 12,
                    highlights = -16,
                    shadows = 8,
                    saturation = -6,
                    temperature = -20,
                    clarity = 10,
                    vignette = 14,
                ),
            ),
        ),
        FilterOption(
            id = "cyberpunk",
            categoryIds = setOf(NIGHT, CREATIVE),
            nameRes = R.string.gs_filter_cyberpunk,
            recipe = FilterRecipe(
                redShift = 18,
                greenShift = -8,
                blueShift = 24,
                adjustments = Adjustments(
                    exposure = -6,
                    contrast = 28,
                    highlights = -22,
                    shadows = -12,
                    saturation = 22,
                    vibrance = 24,
                    tint = 22,
                    clarity = 20,
                    vignette = 24,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "purple",
            categoryIds = setOf(CREATIVE, AESTHETIC),
            nameRes = R.string.gs_filter_purple,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = -6,
                blueShift = 18,
                adjustments = Adjustments(
                    brightness = 3,
                    contrast = 10,
                    highlights = -10,
                    saturation = 6,
                    vibrance = 14,
                    tint = 24,
                    fade = 6,
                ),
            ),
        ),
        FilterOption(
            id = "dream",
            categoryIds = setOf(CREATIVE, AESTHETIC),
            nameRes = R.string.gs_filter_dream,
            recipe = FilterRecipe(
                redShift = 10,
                greenShift = 4,
                blueShift = 12,
                adjustments = Adjustments(
                    brightness = 10,
                    exposure = 4,
                    contrast = -20,
                    highlights = -16,
                    shadows = 14,
                    saturation = -6,
                    vibrance = 10,
                    tint = 10,
                    clarity = -14,
                    fade = 14,
                ),
            ),
        ),
        FilterOption(
            id = "fantasy",
            categoryIds = setOf(CREATIVE),
            nameRes = R.string.gs_filter_fantasy,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 10,
                blueShift = 16,
                adjustments = Adjustments(
                    brightness = 6,
                    contrast = 8,
                    highlights = -12,
                    shadows = 8,
                    saturation = 14,
                    vibrance = 20,
                    tint = 12,
                    clarity = 8,
                    fade = 6,
                ),
            ),
        ),
        FilterOption(
            id = "pencil",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_pencil,
            recipe = FilterRecipe(
                effect = FilterEffect.Pencil,
                effectStrength = 90,
                effectThreshold = 48,
                effectTone = 45,
                adjustments = Adjustments(
                    fade = 8,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "soft_sketch",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_soft_sketch,
            recipe = FilterRecipe(
                effect = FilterEffect.Sketch,
                effectStrength = 58,
                effectThreshold = 58,
                effectTone = 12,
                adjustments = Adjustments(
                    fade = 18,
                    grain = 3,
                ),
            ),
        ),
        FilterOption(
            id = "color_pencil",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_color_pencil,
            recipe = FilterRecipe(
                effect = FilterEffect.ColorPencil,
                effectStrength = 78,
                effectThreshold = 46,
                effectTone = 78,
                adjustments = Adjustments(
                    saturation = 8,
                    vibrance = 10,
                    fade = 8,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "fine_line",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_fine_line,
            recipe = FilterRecipe(
                effect = FilterEffect.Ink,
                effectStrength = 56,
                effectThreshold = 36,
                adjustments = Adjustments(
                    fade = 4,
                ),
            ),
        ),
        FilterOption(
            id = "ink",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_ink,
            recipe = FilterRecipe(
                effect = FilterEffect.Ink,
                effectStrength = 92,
                effectThreshold = 45,
                adjustments = Adjustments(
                    grain = 2,
                ),
            ),
        ),
        FilterOption(
            id = "manga",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_manga,
            recipe = FilterRecipe(
                effect = FilterEffect.Ink,
                effectStrength = 100,
                effectThreshold = 52,
                adjustments = Adjustments(
                    vignette = 6,
                ),
            ),
        ),
        FilterOption(
            id = "charcoal",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_charcoal,
            recipe = FilterRecipe(
                effect = FilterEffect.Charcoal,
                effectStrength = 94,
                effectThreshold = 40,
                effectTone = 72,
                adjustments = Adjustments(
                    grain = 18,
                    vignette = 10,
                ),
            ),
        ),
        FilterOption(
            id = "cross_hatch",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_cross_hatch,
            recipe = FilterRecipe(
                effect = FilterEffect.CrossHatch,
                effectStrength = 82,
                effectThreshold = 44,
                effectTone = 50,
                adjustments = Adjustments(
                    grain = 5,
                ),
            ),
        ),
    )

    val defaultCategory: FilterCategory = categories.first()
    val default: FilterOption = options.first { it.id == ORIGINAL }
    val pack: FilterPack = FilterPack(
        categories = categories,
        options = options,
        defaultCategory = defaultCategory,
        defaultFilter = default,
    )

    fun filtersForCategory(categoryId: String): List<FilterOption> =
        pack.filtersForCategory(categoryId)

    fun categoryForFilter(filter: FilterOption): FilterCategory? =
        pack.categoryForFilter(filter)

    private const val ORIGINAL = "original"
    private const val POPULAR = "popular"
    private const val NATURAL = "natural"
    private const val FILM = "film"
    private const val VINTAGE = "vintage"
    private const val WARM = "warm"
    private const val COOL = "cool"
    private const val PORTRAIT = "portrait"
    private const val FOOD = "food"
    private const val LANDSCAPE = "landscape"
    private const val NIGHT = "night"
    private const val CINEMATIC = "cinematic"
    private const val BLACK_WHITE = "black_white"
    private const val AESTHETIC = "aesthetic"
    private const val CREATIVE = "creative"
    private const val ART = "art"
}

