package com.gsfilter.filter

object FilterCatalog {

    val categories: List<FilterCategory> = listOf(
        FilterCategory(id = POPULAR, nameRes = R.string.gs_category_popular),
        FilterCategory(id = PORTRAIT, nameRes = R.string.gs_category_portrait),
        FilterCategory(id = NATURAL, nameRes = R.string.gs_category_natural),
        FilterCategory(id = FOOD, nameRes = R.string.gs_category_food),
        FilterCategory(id = LANDSCAPE, nameRes = R.string.gs_category_landscape),
        FilterCategory(id = NIGHT, nameRes = R.string.gs_category_night),
        FilterCategory(id = FILM, nameRes = R.string.gs_category_film),
        FilterCategory(id = CINEMATIC, nameRes = R.string.gs_category_cinematic),
        FilterCategory(id = VINTAGE, nameRes = R.string.gs_category_vintage),
        FilterCategory(id = BLACK_WHITE, nameRes = R.string.gs_category_black_white),
        FilterCategory(id = WARM, nameRes = R.string.gs_category_warm),
        FilterCategory(id = COOL, nameRes = R.string.gs_category_cool),
        FilterCategory(id = AESTHETIC, nameRes = R.string.gs_category_aesthetic),
        FilterCategory(id = CREATIVE, nameRes = R.string.gs_category_creative),
        FilterCategory(id = ART, nameRes = R.string.gs_category_art),
    )

    val options: List<FilterOption> = listOf(
        FilterOption(
            id = ORIGINAL,
            categoryIds = emptySet(),
            nameRes = R.string.gs_action_original,
            recipe = FilterRecipe(),
        ),
        FilterOption(
            id = "fresh",
            categoryIds = setOf(POPULAR, NATURAL),
            nameRes = R.string.gs_filter_fresh,
            recipe = FilterRecipe(
                redShift = 4,
                greenShift = 6,
                blueShift = 4,
                adjustments = Adjustments(
                    exposure = 6,
                    contrast = 4,
                    saturation = 8,
                    vibrance = 12,
                    clarity = 4,
                ),
            ),
        ),
        FilterOption(
            id = "portra",
            categoryIds = setOf(FILM, PORTRAIT),
            nameRes = R.string.gs_filter_portra,
            recipe = FilterRecipe(
                redShift = 10,
                greenShift = 3,
                blueShift = -4,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -6,
                    highlights = -12,
                    shadows = 8,
                    saturation = -6,
                    temperature = 6,
                    tint = 4,
                    sharpness = 8,
                ),
            ),
        ),
        FilterOption(
            id = "retro",
            categoryIds = setOf(VINTAGE),
            nameRes = R.string.gs_filter_retro,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = -4,
                blueShift = -12,
                adjustments = Adjustments(
                    contrast = -12,
                    saturation = -18,
                    temperature = 12,
                    fade = 20,
                    vignette = 10,
                    grain = 14,
                ),
            ),
        ),
        FilterOption(
            id = "warm",
            categoryIds = setOf(POPULAR, WARM),
            nameRes = R.string.gs_filter_warm,
            recipe = FilterRecipe(
                redShift = 18,
                greenShift = 6,
                blueShift = -10,
                adjustments = Adjustments(
                    exposure = 4,
                    contrast = 6,
                    saturation = 8,
                    temperature = 18,
                ),
            ),
        ),
        FilterOption(
            id = "cool",
            categoryIds = setOf(COOL),
            nameRes = R.string.gs_filter_cool,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 4,
                blueShift = 18,
                adjustments = Adjustments(
                    contrast = 4,
                    saturation = -4,
                    temperature = -18,
                    tint = -6,
                    clarity = 8,
                ),
            ),
        ),
        FilterOption(
            id = "skin",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_skin,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = 2,
                blueShift = -6,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -8,
                    highlights = -10,
                    shadows = 6,
                    saturation = -4,
                    temperature = 8,
                    tint = 5,
                    sharpness = 4,
                ),
            ),
        ),
        FilterOption(
            id = "tasty",
            categoryIds = setOf(POPULAR, FOOD),
            nameRes = R.string.gs_filter_tasty,
            recipe = FilterRecipe(
                redShift = 14,
                greenShift = 8,
                blueShift = -4,
                adjustments = Adjustments(
                    contrast = 8,
                    saturation = 16,
                    vibrance = 14,
                    temperature = 8,
                    clarity = 8,
                ),
            ),
        ),
        FilterOption(
            id = "cinema",
            categoryIds = setOf(CINEMATIC),
            nameRes = R.string.gs_filter_cinema,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 8,
                blueShift = 10,
                adjustments = Adjustments(
                    exposure = -4,
                    contrast = 18,
                    highlights = -18,
                    shadows = -8,
                    saturation = -8,
                    clarity = 10,
                    vignette = 18,
                ),
            ),
        ),
        FilterOption(
            id = "mono",
            categoryIds = setOf(POPULAR, BLACK_WHITE),
            nameRes = R.string.gs_filter_mono,
            recipe = FilterRecipe(
                isMonochrome = true,
                adjustments = Adjustments(
                    contrast = 14,
                    clarity = 8,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "clear",
            categoryIds = setOf(POPULAR, NATURAL),
            nameRes = R.string.gs_filter_clear,
            recipe = FilterRecipe(
                redShift = 2,
                greenShift = 4,
                blueShift = 3,
                adjustments = Adjustments(
                    exposure = 4,
                    contrast = 6,
                    highlights = -8,
                    shadows = 6,
                    vibrance = 8,
                    clarity = 6,
                ),
            ),
        ),
        FilterOption(
            id = "airy",
            categoryIds = setOf(NATURAL),
            nameRes = R.string.gs_filter_airy,
            recipe = FilterRecipe(
                redShift = 4,
                greenShift = 4,
                blueShift = 6,
                adjustments = Adjustments(
                    brightness = 6,
                    exposure = 6,
                    contrast = -10,
                    highlights = -10,
                    saturation = -6,
                    fade = 8,
                ),
            ),
        ),
        FilterOption(
            id = "fuji",
            categoryIds = setOf(FILM),
            nameRes = R.string.gs_filter_fuji,
            recipe = FilterRecipe(
                redShift = 2,
                greenShift = 8,
                blueShift = 6,
                adjustments = Adjustments(
                    contrast = 10,
                    highlights = -14,
                    shadows = 6,
                    saturation = 8,
                    temperature = -4,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "gold",
            categoryIds = setOf(POPULAR, FILM),
            nameRes = R.string.gs_filter_gold,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = 8,
                blueShift = -8,
                adjustments = Adjustments(
                    contrast = 8,
                    highlights = -8,
                    saturation = 10,
                    temperature = 16,
                    fade = 6,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "arctic",
            categoryIds = setOf(COOL),
            nameRes = R.string.gs_filter_arctic,
            recipe = FilterRecipe(
                redShift = -12,
                greenShift = 2,
                blueShift = 22,
                adjustments = Adjustments(
                    exposure = 2,
                    contrast = 8,
                    saturation = -8,
                    temperature = -24,
                    clarity = 10,
                ),
            ),
        ),
        FilterOption(
            id = "peach",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_peach,
            recipe = FilterRecipe(
                redShift = 14,
                greenShift = 4,
                blueShift = -8,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -10,
                    highlights = -8,
                    saturation = -4,
                    temperature = 10,
                    tint = 8,
                    sharpness = 4,
                ),
            ),
        ),
        FilterOption(
            id = "crispy",
            categoryIds = setOf(FOOD),
            nameRes = R.string.gs_filter_crispy,
            recipe = FilterRecipe(
                redShift = 10,
                greenShift = 10,
                blueShift = -4,
                adjustments = Adjustments(
                    contrast = 14,
                    saturation = 18,
                    vibrance = 18,
                    clarity = 14,
                    sharpness = 10,
                ),
            ),
        ),
        FilterOption(
            id = "teal_orange",
            categoryIds = setOf(POPULAR, CINEMATIC),
            nameRes = R.string.gs_filter_teal_orange,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = 4,
                blueShift = 8,
                adjustments = Adjustments(
                    exposure = -4,
                    contrast = 22,
                    highlights = -16,
                    shadows = -10,
                    saturation = -6,
                    temperature = 8,
                    tint = -8,
                    clarity = 12,
                    vignette = 20,
                ),
            ),
        ),
        FilterOption(
            id = "noir",
            categoryIds = setOf(CINEMATIC, BLACK_WHITE),
            nameRes = R.string.gs_filter_noir,
            recipe = FilterRecipe(
                isMonochrome = true,
                adjustments = Adjustments(
                    exposure = -6,
                    contrast = 26,
                    highlights = -20,
                    shadows = -12,
                    clarity = 16,
                    vignette = 24,
                    grain = 12,
                ),
            ),
        ),
        FilterOption(
            id = "matte",
            categoryIds = setOf(BLACK_WHITE),
            nameRes = R.string.gs_filter_matte,
            recipe = FilterRecipe(
                isMonochrome = true,
                adjustments = Adjustments(
                    contrast = -8,
                    highlights = -8,
                    shadows = 10,
                    fade = 18,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "cream",
            categoryIds = setOf(POPULAR, PORTRAIT),
            nameRes = R.string.gs_filter_cream,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = 6,
                blueShift = -6,
                adjustments = Adjustments(
                    brightness = 6,
                    contrast = -12,
                    highlights = -8,
                    shadows = 8,
                    saturation = -6,
                    temperature = 8,
                    tint = 4,
                    fade = 6,
                ),
            ),
        ),
        FilterOption(
            id = "glow",
            categoryIds = setOf(POPULAR, PORTRAIT),
            nameRes = R.string.gs_filter_glow,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 6,
                blueShift = 2,
                adjustments = Adjustments(
                    brightness = 8,
                    exposure = 6,
                    contrast = -8,
                    highlights = -12,
                    shadows = 6,
                    vibrance = 10,
                    clarity = -6,
                ),
            ),
        ),
        FilterOption(
            id = "kodak",
            categoryIds = setOf(FILM),
            nameRes = R.string.gs_filter_kodak,
            recipe = FilterRecipe(
                redShift = 14,
                greenShift = 6,
                blueShift = -6,
                adjustments = Adjustments(
                    contrast = 12,
                    highlights = -12,
                    shadows = 4,
                    saturation = 10,
                    temperature = 6,
                    fade = 8,
                    grain = 10,
                ),
            ),
        ),
        FilterOption(
            id = "sunset",
            categoryIds = setOf(POPULAR, WARM),
            nameRes = R.string.gs_filter_sunset,
            recipe = FilterRecipe(
                redShift = 24,
                greenShift = 6,
                blueShift = -18,
                adjustments = Adjustments(
                    exposure = -2,
                    contrast = 12,
                    highlights = -16,
                    saturation = 12,
                    vibrance = 10,
                    temperature = 24,
                    vignette = 10,
                ),
            ),
        ),
        FilterOption(
            id = "mist",
            categoryIds = setOf(COOL),
            nameRes = R.string.gs_filter_mist,
            recipe = FilterRecipe(
                redShift = -4,
                greenShift = 4,
                blueShift = 12,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -14,
                    highlights = -12,
                    shadows = 10,
                    saturation = -12,
                    temperature = -10,
                    fade = 12,
                ),
            ),
        ),
        FilterOption(
            id = "cafe",
            categoryIds = setOf(FOOD),
            nameRes = R.string.gs_filter_cafe,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = 8,
                blueShift = -10,
                adjustments = Adjustments(
                    contrast = 6,
                    saturation = 10,
                    vibrance = 8,
                    temperature = 16,
                    tint = 4,
                    fade = 8,
                ),
            ),
        ),
        FilterOption(
            id = "drama",
            categoryIds = setOf(CINEMATIC),
            nameRes = R.string.gs_filter_drama,
            recipe = FilterRecipe(
                redShift = -4,
                greenShift = 4,
                blueShift = 8,
                adjustments = Adjustments(
                    exposure = -8,
                    contrast = 28,
                    highlights = -22,
                    shadows = -16,
                    saturation = -12,
                    clarity = 18,
                    vignette = 26,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "epic",
            categoryIds = setOf(CINEMATIC),
            nameRes = R.string.gs_filter_epic,
            recipe = FilterRecipe(
                redShift = 6,
                greenShift = 2,
                blueShift = 8,
                adjustments = Adjustments(
                    exposure = -4,
                    contrast = 24,
                    highlights = -20,
                    shadows = -8,
                    saturation = -6,
                    clarity = 18,
                    vignette = 20,
                ),
            ),
        ),
        FilterOption(
            id = "blockbuster",
            categoryIds = setOf(POPULAR, CINEMATIC),
            nameRes = R.string.gs_filter_blockbuster,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = 2,
                blueShift = 10,
                adjustments = Adjustments(
                    exposure = -6,
                    contrast = 30,
                    highlights = -24,
                    shadows = -14,
                    saturation = -10,
                    temperature = 10,
                    tint = -10,
                    clarity = 20,
                    vignette = 24,
                    grain = 4,
                ),
            ),
        ),
        FilterOption(
            id = "arthouse",
            categoryIds = setOf(CINEMATIC),
            nameRes = R.string.gs_filter_arthouse,
            recipe = FilterRecipe(
                redShift = 4,
                greenShift = -2,
                blueShift = 6,
                adjustments = Adjustments(
                    brightness = -2,
                    contrast = -6,
                    highlights = -14,
                    shadows = 12,
                    saturation = -18,
                    tint = 6,
                    fade = 14,
                    vignette = 16,
                    grain = 12,
                ),
            ),
        ),
        FilterOption(
            id = "pure",
            categoryIds = setOf(NATURAL),
            nameRes = R.string.gs_filter_pure,
            recipe = FilterRecipe(
                redShift = 2,
                greenShift = 3,
                blueShift = 2,
                adjustments = Adjustments(
                    exposure = 3,
                    contrast = -4,
                    highlights = -6,
                    shadows = 4,
                    saturation = -2,
                ),
            ),
        ),
        FilterOption(
            id = "soft",
            categoryIds = setOf(POPULAR, PORTRAIT),
            nameRes = R.string.gs_filter_soft,
            recipe = FilterRecipe(
                redShift = 6,
                greenShift = 4,
                blueShift = 2,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -12,
                    highlights = -10,
                    shadows = 8,
                    saturation = -8,
                    clarity = -8,
                    fade = 6,
                ),
            ),
        ),
        FilterOption(
            id = "clear_day",
            categoryIds = setOf(LANDSCAPE),
            nameRes = R.string.gs_filter_clear_day,
            recipe = FilterRecipe(
                redShift = 2,
                greenShift = 6,
                blueShift = 8,
                adjustments = Adjustments(
                    exposure = 5,
                    contrast = 8,
                    highlights = -12,
                    shadows = 6,
                    saturation = 6,
                    clarity = 10,
                ),
            ),
        ),
        FilterOption(
            id = "blush",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_blush,
            recipe = FilterRecipe(
                redShift = 14,
                greenShift = 2,
                blueShift = -6,
                adjustments = Adjustments(
                    brightness = 5,
                    contrast = -10,
                    highlights = -8,
                    shadows = 6,
                    saturation = -4,
                    temperature = 6,
                    tint = 10,
                    fade = 4,
                ),
            ),
        ),
        FilterOption(
            id = "rosy",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_rosy,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = 4,
                blueShift = -6,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -8,
                    saturation = -2,
                    temperature = 8,
                    tint = 12,
                    fade = 5,
                ),
            ),
        ),
        FilterOption(
            id = "tan",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_tan,
            recipe = FilterRecipe(
                redShift = 18,
                greenShift = 8,
                blueShift = -12,
                adjustments = Adjustments(
                    exposure = -2,
                    contrast = 8,
                    highlights = -10,
                    shadows = 6,
                    saturation = 4,
                    temperature = 16,
                    vignette = 8,
                ),
            ),
        ),
        FilterOption(
            id = "beauty",
            categoryIds = setOf(POPULAR, PORTRAIT),
            nameRes = R.string.gs_filter_beauty,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 4,
                blueShift = -2,
                adjustments = Adjustments(
                    brightness = 6,
                    exposure = 4,
                    contrast = -8,
                    highlights = -10,
                    shadows = 6,
                    vibrance = 6,
                    clarity = -6,
                ),
            ),
        ),
        FilterOption(
            id = "amber",
            categoryIds = setOf(WARM),
            nameRes = R.string.gs_filter_amber,
            recipe = FilterRecipe(
                redShift = 22,
                greenShift = 8,
                blueShift = -14,
                adjustments = Adjustments(
                    contrast = 8,
                    saturation = 8,
                    temperature = 24,
                    shadows = 4,
                    fade = 4,
                ),
            ),
        ),
        FilterOption(
            id = "caramel",
            categoryIds = setOf(WARM),
            nameRes = R.string.gs_filter_caramel,
            recipe = FilterRecipe(
                redShift = 20,
                greenShift = 10,
                blueShift = -14,
                adjustments = Adjustments(
                    contrast = 6,
                    highlights = -8,
                    shadows = 10,
                    saturation = 6,
                    temperature = 18,
                    fade = 8,
                ),
            ),
        ),
        FilterOption(
            id = "golden_hour",
            categoryIds = setOf(POPULAR, LANDSCAPE),
            nameRes = R.string.gs_filter_golden_hour,
            recipe = FilterRecipe(
                redShift = 26,
                greenShift = 10,
                blueShift = -18,
                adjustments = Adjustments(
                    exposure = 3,
                    contrast = 12,
                    highlights = -18,
                    shadows = 8,
                    saturation = 10,
                    vibrance = 10,
                    temperature = 26,
                    vignette = 8,
                ),
            ),
        ),
        FilterOption(
            id = "cozy",
            categoryIds = setOf(WARM),
            nameRes = R.string.gs_filter_cozy,
            recipe = FilterRecipe(
                redShift = 18,
                greenShift = 8,
                blueShift = -10,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -4,
                    highlights = -10,
                    shadows = 8,
                    saturation = 4,
                    temperature = 18,
                    fade = 8,
                ),
            ),
        ),
        FilterOption(
            id = "blue_mist",
            categoryIds = setOf(COOL),
            nameRes = R.string.gs_filter_blue_mist,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 4,
                blueShift = 18,
                adjustments = Adjustments(
                    brightness = 5,
                    contrast = -16,
                    highlights = -14,
                    shadows = 10,
                    saturation = -14,
                    temperature = -18,
                    fade = 14,
                ),
            ),
        ),
        FilterOption(
            id = "winter",
            categoryIds = setOf(LANDSCAPE),
            nameRes = R.string.gs_filter_winter,
            recipe = FilterRecipe(
                redShift = -12,
                greenShift = 2,
                blueShift = 20,
                adjustments = Adjustments(
                    exposure = 3,
                    contrast = 10,
                    highlights = -16,
                    saturation = -12,
                    temperature = -22,
                    clarity = 12,
                ),
            ),
        ),
        FilterOption(
            id = "steel",
            categoryIds = setOf(COOL),
            nameRes = R.string.gs_filter_steel,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 0,
                blueShift = 14,
                adjustments = Adjustments(
                    exposure = -2,
                    contrast = 18,
                    highlights = -16,
                    shadows = -8,
                    saturation = -18,
                    temperature = -18,
                    clarity = 14,
                ),
            ),
        ),
        FilterOption(
            id = "cyan_clean",
            categoryIds = setOf(COOL),
            nameRes = R.string.gs_filter_cyan_clean,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 8,
                blueShift = 16,
                adjustments = Adjustments(
                    exposure = 4,
                    contrast = 8,
                    highlights = -10,
                    saturation = -4,
                    temperature = -12,
                    tint = -8,
                    clarity = 10,
                ),
            ),
        ),
        FilterOption(
            id = "grain_film",
            categoryIds = setOf(FILM),
            nameRes = R.string.gs_filter_grain_film,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 4,
                blueShift = -4,
                adjustments = Adjustments(
                    contrast = 10,
                    highlights = -14,
                    shadows = 6,
                    saturation = 4,
                    temperature = 4,
                    fade = 6,
                    grain = 18,
                ),
            ),
        ),
        FilterOption(
            id = "fade",
            categoryIds = setOf(VINTAGE),
            nameRes = R.string.gs_filter_fade,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 2,
                blueShift = -6,
                adjustments = Adjustments(
                    contrast = -16,
                    highlights = -12,
                    shadows = 14,
                    saturation = -16,
                    fade = 24,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "dust",
            categoryIds = setOf(VINTAGE),
            nameRes = R.string.gs_filter_dust,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = 4,
                blueShift = -10,
                adjustments = Adjustments(
                    contrast = -10,
                    highlights = -10,
                    shadows = 8,
                    saturation = -18,
                    temperature = 10,
                    fade = 18,
                    vignette = 10,
                    grain = 16,
                ),
            ),
        ),
        FilterOption(
            id = "oldie",
            categoryIds = setOf(VINTAGE),
            nameRes = R.string.gs_filter_oldie,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = 4,
                blueShift = -14,
                adjustments = Adjustments(
                    brightness = -2,
                    contrast = -14,
                    highlights = -10,
                    shadows = 12,
                    saturation = -22,
                    temperature = 14,
                    tint = 4,
                    fade = 22,
                    grain = 14,
                ),
            ),
        ),
        FilterOption(
            id = "nineties",
            categoryIds = setOf(VINTAGE),
            nameRes = R.string.gs_filter_nineties,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = -2,
                blueShift = -8,
                adjustments = Adjustments(
                    contrast = -4,
                    highlights = -14,
                    shadows = 10,
                    saturation = -10,
                    tint = 8,
                    fade = 12,
                    grain = 10,
                ),
            ),
        ),
        FilterOption(
            id = "retro_matte",
            categoryIds = setOf(VINTAGE, BLACK_WHITE),
            nameRes = R.string.gs_filter_retro_matte,
            recipe = FilterRecipe(
                redShift = 6,
                greenShift = 0,
                blueShift = -8,
                adjustments = Adjustments(
                    contrast = -10,
                    highlights = -10,
                    shadows = 12,
                    saturation = -24,
                    fade = 20,
                    grain = 10,
                ),
            ),
        ),
        FilterOption(
            id = "bleach",
            categoryIds = setOf(CINEMATIC),
            nameRes = R.string.gs_filter_bleach,
            recipe = FilterRecipe(
                redShift = 6,
                greenShift = 2,
                blueShift = -2,
                adjustments = Adjustments(
                    exposure = 2,
                    contrast = 28,
                    highlights = -18,
                    shadows = -10,
                    saturation = -28,
                    clarity = 18,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "high_contrast",
            categoryIds = setOf(BLACK_WHITE),
            nameRes = R.string.gs_filter_high_contrast,
            recipe = FilterRecipe(
                isMonochrome = true,
                adjustments = Adjustments(
                    exposure = -2,
                    contrast = 34,
                    highlights = -16,
                    shadows = -12,
                    clarity = 18,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "soft_mono",
            categoryIds = setOf(BLACK_WHITE, PORTRAIT),
            nameRes = R.string.gs_filter_soft_mono,
            recipe = FilterRecipe(
                isMonochrome = true,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -8,
                    highlights = -8,
                    shadows = 8,
                    clarity = -4,
                    fade = 12,
                    grain = 4,
                ),
            ),
        ),
        FilterOption(
            id = "warm_plate",
            categoryIds = setOf(FOOD),
            nameRes = R.string.gs_filter_warm_plate,
            recipe = FilterRecipe(
                redShift = 18,
                greenShift = 10,
                blueShift = -8,
                adjustments = Adjustments(
                    contrast = 8,
                    highlights = -10,
                    saturation = 14,
                    vibrance = 12,
                    temperature = 16,
                    clarity = 8,
                ),
            ),
        ),
        FilterOption(
            id = "forest",
            categoryIds = setOf(LANDSCAPE),
            nameRes = R.string.gs_filter_forest,
            recipe = FilterRecipe(
                redShift = -4,
                greenShift = 18,
                blueShift = -4,
                adjustments = Adjustments(
                    exposure = 2,
                    contrast = 12,
                    highlights = -16,
                    shadows = 8,
                    saturation = 12,
                    vibrance = 16,
                    temperature = -4,
                    clarity = 12,
                ),
            ),
        ),
        FilterOption(
            id = "ocean",
            categoryIds = setOf(LANDSCAPE),
            nameRes = R.string.gs_filter_ocean,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 8,
                blueShift = 20,
                adjustments = Adjustments(
                    exposure = 3,
                    contrast = 12,
                    highlights = -14,
                    saturation = 10,
                    vibrance = 16,
                    temperature = -14,
                    clarity = 14,
                ),
            ),
        ),
        FilterOption(
            id = "sky",
            categoryIds = setOf(LANDSCAPE),
            nameRes = R.string.gs_filter_sky,
            recipe = FilterRecipe(
                redShift = -4,
                greenShift = 6,
                blueShift = 18,
                adjustments = Adjustments(
                    brightness = 3,
                    exposure = 4,
                    contrast = 8,
                    highlights = -18,
                    saturation = 8,
                    vibrance = 14,
                    temperature = -10,
                    clarity = 10,
                ),
            ),
        ),
        FilterOption(
            id = "travel",
            categoryIds = setOf(POPULAR, LANDSCAPE),
            nameRes = R.string.gs_filter_travel,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 8,
                blueShift = 2,
                adjustments = Adjustments(
                    exposure = 4,
                    contrast = 14,
                    highlights = -12,
                    shadows = 6,
                    saturation = 12,
                    vibrance = 14,
                    temperature = 6,
                    clarity = 12,
                ),
            ),
        ),
        FilterOption(
            id = "beige",
            categoryIds = setOf(AESTHETIC),
            nameRes = R.string.gs_filter_beige,
            recipe = FilterRecipe(
                redShift = 12,
                greenShift = 6,
                blueShift = -8,
                adjustments = Adjustments(
                    brightness = 5,
                    contrast = -12,
                    highlights = -10,
                    shadows = 10,
                    saturation = -14,
                    temperature = 10,
                    fade = 10,
                ),
            ),
        ),
        FilterOption(
            id = "latte",
            categoryIds = setOf(AESTHETIC),
            nameRes = R.string.gs_filter_latte,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = 8,
                blueShift = -10,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -10,
                    highlights = -12,
                    shadows = 12,
                    saturation = -10,
                    temperature = 14,
                    fade = 12,
                ),
            ),
        ),
        FilterOption(
            id = "pink",
            categoryIds = setOf(AESTHETIC),
            nameRes = R.string.gs_filter_pink,
            recipe = FilterRecipe(
                redShift = 18,
                greenShift = 2,
                blueShift = 4,
                adjustments = Adjustments(
                    brightness = 6,
                    contrast = -10,
                    highlights = -8,
                    saturation = -8,
                    temperature = 4,
                    tint = 18,
                    fade = 8,
                ),
            ),
        ),
        FilterOption(
            id = "dreamy",
            categoryIds = setOf(AESTHETIC),
            nameRes = R.string.gs_filter_dreamy,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 4,
                blueShift = 8,
                adjustments = Adjustments(
                    brightness = 8,
                    exposure = 4,
                    contrast = -18,
                    highlights = -14,
                    shadows = 12,
                    saturation = -8,
                    clarity = -12,
                    fade = 12,
                ),
            ),
        ),
        FilterOption(
            id = "minimal",
            categoryIds = setOf(AESTHETIC),
            nameRes = R.string.gs_filter_minimal,
            recipe = FilterRecipe(
                redShift = 2,
                greenShift = 2,
                blueShift = 2,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = -8,
                    highlights = -8,
                    shadows = 6,
                    saturation = -18,
                    fade = 6,
                ),
            ),
        ),
        FilterOption(
            id = "neon",
            categoryIds = setOf(POPULAR, NIGHT, CREATIVE),
            nameRes = R.string.gs_filter_neon,
            recipe = FilterRecipe(
                redShift = 10,
                greenShift = -4,
                blueShift = 18,
                adjustments = Adjustments(
                    exposure = -4,
                    contrast = 24,
                    highlights = -24,
                    shadows = -12,
                    saturation = 16,
                    vibrance = 22,
                    tint = 14,
                    clarity = 18,
                    vignette = 22,
                ),
            ),
        ),
        FilterOption(
            id = "city",
            categoryIds = setOf(NIGHT),
            nameRes = R.string.gs_filter_city,
            recipe = FilterRecipe(
                redShift = 4,
                greenShift = 2,
                blueShift = 12,
                adjustments = Adjustments(
                    exposure = -2,
                    contrast = 20,
                    highlights = -20,
                    shadows = -8,
                    saturation = -4,
                    temperature = -8,
                    clarity = 14,
                    vignette = 18,
                ),
            ),
        ),
        FilterOption(
            id = "night",
            categoryIds = setOf(NIGHT),
            nameRes = R.string.gs_filter_night,
            recipe = FilterRecipe(
                redShift = -6,
                greenShift = 0,
                blueShift = 16,
                adjustments = Adjustments(
                    exposure = -10,
                    contrast = 22,
                    highlights = -18,
                    shadows = 10,
                    saturation = -10,
                    temperature = -18,
                    clarity = 12,
                    vignette = 24,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "blue_hour",
            categoryIds = setOf(NIGHT, LANDSCAPE),
            nameRes = R.string.gs_filter_blue_hour,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 4,
                blueShift = 18,
                adjustments = Adjustments(
                    exposure = -4,
                    contrast = 12,
                    highlights = -16,
                    shadows = 8,
                    saturation = -6,
                    temperature = -20,
                    clarity = 10,
                    vignette = 14,
                ),
            ),
        ),
        FilterOption(
            id = "cyberpunk",
            categoryIds = setOf(NIGHT, CREATIVE),
            nameRes = R.string.gs_filter_cyberpunk,
            recipe = FilterRecipe(
                redShift = 18,
                greenShift = -8,
                blueShift = 24,
                adjustments = Adjustments(
                    exposure = -6,
                    contrast = 28,
                    highlights = -22,
                    shadows = -12,
                    saturation = 22,
                    vibrance = 24,
                    tint = 22,
                    clarity = 20,
                    vignette = 24,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "purple",
            categoryIds = setOf(CREATIVE),
            nameRes = R.string.gs_filter_purple,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = -6,
                blueShift = 18,
                adjustments = Adjustments(
                    brightness = 3,
                    contrast = 10,
                    highlights = -10,
                    saturation = 6,
                    vibrance = 14,
                    tint = 24,
                    fade = 6,
                ),
            ),
        ),
        FilterOption(
            id = "dream",
            categoryIds = setOf(CREATIVE),
            nameRes = R.string.gs_filter_dream,
            recipe = FilterRecipe(
                redShift = 10,
                greenShift = 4,
                blueShift = 12,
                adjustments = Adjustments(
                    brightness = 10,
                    exposure = 4,
                    contrast = -20,
                    highlights = -16,
                    shadows = 14,
                    saturation = -6,
                    vibrance = 10,
                    tint = 10,
                    clarity = -14,
                    fade = 14,
                ),
            ),
        ),
        FilterOption(
            id = "fantasy",
            categoryIds = setOf(CREATIVE),
            nameRes = R.string.gs_filter_fantasy,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 10,
                blueShift = 16,
                adjustments = Adjustments(
                    brightness = 6,
                    contrast = 8,
                    highlights = -12,
                    shadows = 8,
                    saturation = 14,
                    vibrance = 20,
                    tint = 12,
                    clarity = 8,
                    fade = 6,
                ),
            ),
        ),
        FilterOption(
            id = "clean_light",
            categoryIds = setOf(POPULAR, NATURAL),
            nameRes = R.string.gs_filter_clean_light,
            recipe = FilterRecipe(
                redShift = 3,
                greenShift = 5,
                blueShift = 3,
                adjustments = Adjustments(
                    brightness = 4,
                    exposure = 5,
                    contrast = -4,
                    highlights = -10,
                    shadows = 5,
                    saturation = 4,
                    vibrance = 8,
                    clarity = 2,
                ),
            ),
        ),
        FilterOption(
            id = "soft_day",
            categoryIds = setOf(NATURAL),
            nameRes = R.string.gs_filter_soft_day,
            recipe = FilterRecipe(
                redShift = 5,
                greenShift = 5,
                blueShift = 4,
                adjustments = Adjustments(
                    brightness = 7,
                    exposure = 4,
                    contrast = -14,
                    highlights = -12,
                    shadows = 10,
                    saturation = -4,
                    vibrance = 6,
                    clarity = -8,
                    fade = 6,
                ),
            ),
        ),
        FilterOption(
            id = "selfie_clear",
            categoryIds = setOf(POPULAR, PORTRAIT),
            nameRes = R.string.gs_filter_selfie_clear,
            recipe = FilterRecipe(
                redShift = 6,
                greenShift = 5,
                blueShift = 2,
                adjustments = Adjustments(
                    brightness = 5,
                    exposure = 3,
                    contrast = -6,
                    highlights = -8,
                    shadows = 6,
                    saturation = -2,
                    vibrance = 8,
                    temperature = 4,
                    clarity = -2,
                ),
            ),
        ),
        FilterOption(
            id = "soft_portrait",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_soft_portrait,
            recipe = FilterRecipe(
                redShift = 10,
                greenShift = 4,
                blueShift = -4,
                adjustments = Adjustments(
                    brightness = 6,
                    contrast = -16,
                    highlights = -12,
                    shadows = 8,
                    saturation = -8,
                    temperature = 6,
                    tint = 4,
                    clarity = -10,
                    fade = 4,
                ),
            ),
        ),
        FilterOption(
            id = "studio_skin",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_studio_skin,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 3,
                blueShift = -3,
                adjustments = Adjustments(
                    contrast = 8,
                    highlights = -14,
                    shadows = 4,
                    saturation = -4,
                    temperature = 4,
                    tint = 3,
                    sharpness = 4,
                    clarity = 4,
                ),
            ),
        ),
        FilterOption(
            id = "golden_skin",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_golden_skin,
            recipe = FilterRecipe(
                redShift = 18,
                greenShift = 6,
                blueShift = -12,
                adjustments = Adjustments(
                    brightness = 3,
                    exposure = 4,
                    contrast = -6,
                    highlights = -10,
                    saturation = 2,
                    temperature = 16,
                    tint = 3,
                    fade = 4,
                ),
            ),
        ),
        FilterOption(
            id = "indoor_warm",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_indoor_warm,
            recipe = FilterRecipe(
                redShift = 14,
                greenShift = 4,
                blueShift = -8,
                adjustments = Adjustments(
                    exposure = 5,
                    contrast = -8,
                    highlights = -14,
                    shadows = 10,
                    saturation = -2,
                    temperature = 12,
                    tint = 4,
                    clarity = -4,
                ),
            ),
        ),
        FilterOption(
            id = "flash_soft",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_flash_soft,
            recipe = FilterRecipe(
                redShift = 5,
                greenShift = 3,
                blueShift = 6,
                adjustments = Adjustments(
                    brightness = 3,
                    contrast = -12,
                    highlights = -24,
                    shadows = 12,
                    saturation = -8,
                    temperature = -4,
                    clarity = -8,
                    fade = 6,
                ),
            ),
        ),
        FilterOption(
            id = "low_light_skin",
            categoryIds = setOf(PORTRAIT, NIGHT),
            nameRes = R.string.gs_filter_low_light_skin,
            recipe = FilterRecipe(
                redShift = 10,
                greenShift = 2,
                blueShift = 4,
                adjustments = Adjustments(
                    exposure = 7,
                    contrast = 8,
                    highlights = -22,
                    shadows = 16,
                    saturation = -6,
                    temperature = 4,
                    clarity = 8,
                    vignette = 8,
                    grain = 4,
                ),
            ),
        ),
        FilterOption(
            id = "fresh_plate",
            categoryIds = setOf(POPULAR, FOOD),
            nameRes = R.string.gs_filter_fresh_plate,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 10,
                blueShift = -2,
                adjustments = Adjustments(
                    contrast = 10,
                    highlights = -6,
                    saturation = 14,
                    vibrance = 18,
                    temperature = 4,
                    clarity = 8,
                    sharpness = 6,
                ),
            ),
        ),
        FilterOption(
            id = "warm_table",
            categoryIds = setOf(FOOD),
            nameRes = R.string.gs_filter_warm_table,
            recipe = FilterRecipe(
                redShift = 16,
                greenShift = 8,
                blueShift = -8,
                adjustments = Adjustments(
                    exposure = 4,
                    contrast = 6,
                    shadows = 4,
                    saturation = 10,
                    vibrance = 12,
                    temperature = 16,
                    vignette = 6,
                ),
            ),
        ),
        FilterOption(
            id = "deep_teal",
            categoryIds = setOf(CINEMATIC),
            nameRes = R.string.gs_filter_deep_teal,
            recipe = FilterRecipe(
                redShift = -8,
                greenShift = 6,
                blueShift = 14,
                adjustments = Adjustments(
                    exposure = -5,
                    contrast = 24,
                    highlights = -18,
                    shadows = -8,
                    saturation = -8,
                    temperature = -8,
                    tint = -12,
                    clarity = 14,
                    vignette = 20,
                ),
            ),
        ),
        FilterOption(
            id = "fade_drama",
            categoryIds = setOf(CINEMATIC),
            nameRes = R.string.gs_filter_fade_drama,
            recipe = FilterRecipe(
                redShift = 8,
                greenShift = 4,
                blueShift = -4,
                adjustments = Adjustments(
                    exposure = -4,
                    contrast = 16,
                    highlights = -20,
                    shadows = 8,
                    saturation = -12,
                    temperature = 6,
                    fade = 14,
                    vignette = 18,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "midnight_city",
            categoryIds = setOf(NIGHT),
            nameRes = R.string.gs_filter_midnight_city,
            recipe = FilterRecipe(
                redShift = 4,
                greenShift = -4,
                blueShift = 20,
                adjustments = Adjustments(
                    exposure = -8,
                    contrast = 22,
                    highlights = -24,
                    shadows = -10,
                    saturation = 10,
                    vibrance = 16,
                    tint = 10,
                    clarity = 18,
                    vignette = 24,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "sunlit_forest",
            categoryIds = setOf(LANDSCAPE),
            nameRes = R.string.gs_filter_sunlit_forest,
            recipe = FilterRecipe(
                redShift = 10,
                greenShift = 14,
                blueShift = -6,
                adjustments = Adjustments(
                    exposure = 3,
                    contrast = 10,
                    highlights = -8,
                    shadows = 6,
                    saturation = 10,
                    vibrance = 18,
                    temperature = 8,
                    clarity = 12,
                ),
            ),
        ),
        FilterOption(
            id = "pearl_mono",
            categoryIds = setOf(BLACK_WHITE, PORTRAIT),
            nameRes = R.string.gs_filter_pearl_mono,
            recipe = FilterRecipe(
                isMonochrome = true,
                adjustments = Adjustments(
                    brightness = 4,
                    contrast = 6,
                    highlights = -12,
                    shadows = 8,
                    clarity = 4,
                    fade = 10,
                    grain = 4,
                ),
            ),
        ),
        FilterOption(
            id = "lut_clean_portrait",
            categoryIds = setOf(POPULAR, PORTRAIT),
            nameRes = R.string.gs_filter_lut_clean_portrait,
            recipe = FilterRecipe(
                lut = FilterLut.CleanPortrait,
                lutStrength = 100,
                adjustments = Adjustments(
                    brightness = 2,
                    highlights = -8,
                    shadows = 5,
                    clarity = -2,
                ),
            ),
        ),
        FilterOption(
            id = "lut_soft_skin",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_lut_soft_skin,
            recipe = FilterRecipe(
                lut = FilterLut.SoftSkin,
                lutStrength = 100,
                adjustments = Adjustments(
                    brightness = 3,
                    contrast = -6,
                    highlights = -10,
                    shadows = 6,
                    clarity = -8,
                ),
            ),
        ),
        FilterOption(
            id = "lut_golden_portrait",
            categoryIds = setOf(PORTRAIT),
            nameRes = R.string.gs_filter_lut_golden_portrait,
            recipe = FilterRecipe(
                lut = FilterLut.GoldenPortrait,
                lutStrength = 100,
                adjustments = Adjustments(
                    exposure = 2,
                    highlights = -8,
                    temperature = 6,
                    tint = 2,
                ),
            ),
        ),
        FilterOption(
            id = "lut_daylight_fresh",
            categoryIds = setOf(POPULAR, NATURAL),
            nameRes = R.string.gs_filter_lut_daylight_fresh,
            recipe = FilterRecipe(
                lut = FilterLut.DaylightFresh,
                lutStrength = 100,
                adjustments = Adjustments(
                    exposure = 3,
                    highlights = -6,
                    vibrance = 8,
                    clarity = 3,
                ),
            ),
        ),
        FilterOption(
            id = "lut_food_pop",
            categoryIds = setOf(POPULAR, FOOD),
            nameRes = R.string.gs_filter_lut_food_pop,
            recipe = FilterRecipe(
                lut = FilterLut.FoodPop,
                lutStrength = 85,
                adjustments = Adjustments(
                    contrast = 4,
                    saturation = 2,
                    vibrance = 6,
                    clarity = 5,
                ),
            ),
        ),
        FilterOption(
            id = "lut_green_film",
            categoryIds = setOf(LANDSCAPE),
            nameRes = R.string.gs_filter_lut_green_film,
            recipe = FilterRecipe(
                lut = FilterLut.GreenFilm,
                lutStrength = 100,
                adjustments = Adjustments(
                    highlights = -10,
                    shadows = 6,
                    clarity = 6,
                    grain = 4,
                ),
            ),
        ),
        FilterOption(
            id = "lut_teal_cinema",
            categoryIds = setOf(POPULAR, CINEMATIC),
            nameRes = R.string.gs_filter_lut_teal_cinema,
            recipe = FilterRecipe(
                lut = FilterLut.TealCinema,
                lutStrength = 100,
                adjustments = Adjustments(
                    exposure = -3,
                    contrast = 8,
                    highlights = -14,
                    shadows = -4,
                    vignette = 10,
                ),
            ),
        ),
        FilterOption(
            id = "lut_night_mood",
            categoryIds = setOf(NIGHT),
            nameRes = R.string.gs_filter_lut_night_mood,
            recipe = FilterRecipe(
                lut = FilterLut.NightMood,
                lutStrength = 100,
                adjustments = Adjustments(
                    exposure = -6,
                    contrast = 10,
                    highlights = -18,
                    shadows = -6,
                    clarity = 10,
                    vignette = 14,
                ),
            ),
        ),
        FilterOption(
            id = "lut_vintage_fade",
            categoryIds = setOf(VINTAGE),
            nameRes = R.string.gs_filter_lut_vintage_fade,
            recipe = FilterRecipe(
                lut = FilterLut.VintageFade,
                lutStrength = 100,
                adjustments = Adjustments(
                    contrast = -4,
                    highlights = -8,
                    fade = 8,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "lut_editorial_matte",
            categoryIds = setOf(AESTHETIC),
            nameRes = R.string.gs_filter_lut_editorial_matte,
            recipe = FilterRecipe(
                lut = FilterLut.EditorialMatte,
                lutStrength = 100,
                adjustments = Adjustments(
                    contrast = -4,
                    saturation = -4,
                    highlights = -8,
                    shadows = 8,
                    fade = 8,
                ),
            ),
        ),
        FilterOption(
            id = "pencil",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_pencil,
            recipe = FilterRecipe(
                effect = FilterEffect.Pencil,
                effectStrength = 90,
                effectThreshold = 48,
                effectTone = 45,
                adjustments = Adjustments(
                    fade = 8,
                    grain = 8,
                ),
            ),
        ),
        FilterOption(
            id = "soft_sketch",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_soft_sketch,
            recipe = FilterRecipe(
                effect = FilterEffect.Sketch,
                effectStrength = 58,
                effectThreshold = 58,
                effectTone = 12,
                adjustments = Adjustments(
                    fade = 18,
                    grain = 3,
                ),
            ),
        ),
        FilterOption(
            id = "color_pencil",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_color_pencil,
            recipe = FilterRecipe(
                effect = FilterEffect.ColorPencil,
                effectStrength = 78,
                effectThreshold = 46,
                effectTone = 78,
                adjustments = Adjustments(
                    saturation = 8,
                    vibrance = 10,
                    fade = 8,
                    grain = 6,
                ),
            ),
        ),
        FilterOption(
            id = "fine_line",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_fine_line,
            recipe = FilterRecipe(
                effect = FilterEffect.Ink,
                effectStrength = 56,
                effectThreshold = 36,
                adjustments = Adjustments(
                    fade = 4,
                ),
            ),
        ),
        FilterOption(
            id = "ink",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_ink,
            recipe = FilterRecipe(
                effect = FilterEffect.Ink,
                effectStrength = 92,
                effectThreshold = 45,
                adjustments = Adjustments(
                    grain = 2,
                ),
            ),
        ),
        FilterOption(
            id = "charcoal",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_charcoal,
            recipe = FilterRecipe(
                effect = FilterEffect.Charcoal,
                effectStrength = 94,
                effectThreshold = 40,
                effectTone = 72,
                adjustments = Adjustments(
                    grain = 18,
                    vignette = 10,
                ),
            ),
        ),
        FilterOption(
            id = "cross_hatch",
            categoryIds = setOf(ART),
            nameRes = R.string.gs_filter_cross_hatch,
            recipe = FilterRecipe(
                effect = FilterEffect.CrossHatch,
                effectStrength = 82,
                effectThreshold = 44,
                effectTone = 50,
                adjustments = Adjustments(
                    grain = 5,
                ),
            ),
        ),
    )

    val defaultCategory: FilterCategory = categories.first()
    val default: FilterOption = options.first { it.id == ORIGINAL }
    val pack: FilterPack = FilterPack(
        categories = categories,
        options = options,
        defaultCategory = defaultCategory,
        defaultFilter = default,
    )

    fun filtersForCategory(categoryId: String): List<FilterOption> {
        val filters = pack.filtersForCategory(categoryId)
        val priority = categoryFilterPriority[categoryId] ?: return filters
        return filters.sortedBy { filter ->
            priority.indexOf(filter.id).takeIf { it >= 0 } ?: Int.MAX_VALUE
        }
    }

    fun categoryForFilter(filter: FilterOption): FilterCategory? =
        pack.categoryForFilter(filter)

    private val categoryFilterPriority: Map<String, List<String>> = mapOf(
        POPULAR to listOf(
            "lut_clean_portrait",
            "lut_daylight_fresh",
            "selfie_clear",
            "fresh",
            "clear",
            "clean_light",
            "lut_food_pop",
            "tasty",
            "lut_teal_cinema",
            "teal_orange",
            "mono",
            "golden_hour",
        ),
        PORTRAIT to listOf(
            "lut_clean_portrait",
            "lut_soft_skin",
            "selfie_clear",
            "lut_golden_portrait",
            "soft_portrait",
            "skin",
            "portra",
            "studio_skin",
            "golden_skin",
            "indoor_warm",
            "low_light_skin",
        ),
        NATURAL to listOf("lut_daylight_fresh", "fresh", "clear", "clean_light", "soft_day", "airy", "pure"),
        FOOD to listOf("lut_food_pop", "tasty", "crispy", "fresh_plate", "warm_plate", "warm_table", "cafe"),
        LANDSCAPE to listOf(
            "lut_green_film",
            "clear_day",
            "golden_hour",
            "sunlit_forest",
            "forest",
            "sky",
            "ocean",
            "travel",
            "winter",
            "blue_hour",
        ),
        NIGHT to listOf(
            "lut_night_mood",
            "midnight_city",
            "city",
            "night",
            "blue_hour",
            "neon",
            "cyberpunk",
            "low_light_skin",
        ),
        FILM to listOf("portra", "fuji", "kodak", "gold", "grain_film"),
        CINEMATIC to listOf(
            "lut_teal_cinema",
            "teal_orange",
            "cinema",
            "blockbuster",
            "deep_teal",
            "fade_drama",
            "noir",
            "epic",
            "bleach",
            "drama",
            "arthouse",
        ),
        VINTAGE to listOf("lut_vintage_fade", "retro", "fade", "dust", "oldie", "nineties", "retro_matte"),
        BLACK_WHITE to listOf("mono", "soft_mono", "pearl_mono", "noir", "high_contrast", "matte", "retro_matte"),
        WARM to listOf("warm", "sunset", "amber", "caramel", "cozy"),
        COOL to listOf("cool", "cyan_clean", "arctic", "blue_mist", "mist", "steel"),
        AESTHETIC to listOf("lut_editorial_matte", "beige", "minimal", "dreamy", "latte", "pink"),
        CREATIVE to listOf("neon", "cyberpunk", "purple", "dream", "fantasy"),
        ART to listOf("pencil", "soft_sketch", "color_pencil", "fine_line", "ink", "charcoal", "cross_hatch"),
    )

    private const val ORIGINAL = "original"
    private const val POPULAR = "popular"
    private const val NATURAL = "natural"
    private const val FILM = "film"
    private const val VINTAGE = "vintage"
    private const val WARM = "warm"
    private const val COOL = "cool"
    private const val PORTRAIT = "portrait"
    private const val FOOD = "food"
    private const val LANDSCAPE = "landscape"
    private const val NIGHT = "night"
    private const val CINEMATIC = "cinematic"
    private const val BLACK_WHITE = "black_white"
    private const val AESTHETIC = "aesthetic"
    private const val CREATIVE = "creative"
    private const val ART = "art"
}

